import { Staff } from '../types';

export const INITIAL_SUOI_LU_STAFF: Omit<Staff, 'created_at' | 'updated_at'>[] = [
  // Ban Giám Hiệu (Quản lí)
  {
    id: 'sl-001',
    ho_ten: 'Lò Văn Việt',
    ma_can_bo: 'CB001',
    chuc_vu: 'Quản lí',
    bo_phan: 'Ban Giám Hiệu',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-10T08:30:00Z',
  },
  {
    id: 'sl-002',
    ho_ten: 'Nguyễn Thị Hoa',
    ma_can_bo: 'CB002',
    chuc_vu: 'Quản lí',
    bo_phan: 'Ban Giám Hiệu',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-10T09:15:00Z',
  },
  {
    id: 'sl-003',
    ho_ten: 'Trần Văn Mạnh',
    ma_can_bo: 'CB003',
    chuc_vu: 'Quản lí',
    bo_phan: 'Ban Giám Hiệu',
    da_cai_dat: false,
    ngay_cai_dat: null,
  },

  // Tổ Giáo Viên THCS (KHTN & KHXH)
  {
    id: 'sl-004',
    ho_ten: 'Cà Văn Sáng',
    ma_can_bo: 'GV001',
    chuc_vu: 'Giáo viên',
    bo_phan: 'Tổ Toán - Khoa học tự nhiên',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-11T07:45:00Z',
  },
  {
    id: 'sl-005',
    ho_ten: 'Lường Thị Minh',
    ma_can_bo: 'GV002',
    chuc_vu: 'Giáo viên',
    bo_phan: 'Tổ Toán - Khoa học tự nhiên',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-11T08:00:00Z',
  },
  {
    id: 'sl-006',
    ho_ten: 'Phạm Hồng Thái',
    ma_can_bo: 'GV003',
    chuc_vu: 'Giáo viên',
    bo_phan: 'Tổ Toán - Khoa học tự nhiên',
    da_cai_dat: false,
    ngay_cai_dat: null,
  },
  {
    id: 'sl-007',
    ho_ten: 'Hoàng Văn Khiêm',
    ma_can_bo: 'GV004',
    chuc_vu: 'Giáo viên',
    bo_phan: 'Tổ Văn - Lịch sử - Địa lý',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-11T09:20:00Z',
  },
  {
    id: 'sl-008',
    ho_ten: 'Quàng Thị Thương',
    ma_can_bo: 'GV005',
    chuc_vu: 'Giáo viên',
    bo_phan: 'Tổ Văn - Lịch sử - Địa lý',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-11T10:10:00Z',
  },
  {
    id: 'sl-009',
    ho_ten: 'Vũ Thanh Tùng',
    ma_can_bo: 'GV006',
    chuc_vu: 'Giáo viên',
    bo_phan: 'Tổ Văn - Lịch sử - Địa lý',
    da_cai_dat: false,
    ngay_cai_dat: null,
  },
  {
    id: 'sl-010',
    ho_ten: 'Lò Thị Mai',
    ma_can_bo: 'GV007',
    chuc_vu: 'Giáo viên',
    bo_phan: 'Tổ Ngoại ngữ - Tin học',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-11T11:00:00Z',
  },
  {
    id: 'sl-011',
    ho_ten: 'Đào Văn Tiến',
    ma_can_bo: 'GV008',
    chuc_vu: 'Giáo viên',
    bo_phan: 'Tổ Ngoại ngữ - Tin học',
    da_cai_dat: false,
    ngay_cai_dat: null,
  },

  // Tổ Giáo Viên Tiểu Học
  {
    id: 'sl-012',
    ho_ten: 'Lò Thị Tuyết',
    ma_can_bo: 'GV009',
    chuc_vu: 'Giáo viên',
    bo_phan: 'Tổ Khối 1 - Khối 2',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-11T13:30:00Z',
  },
  {
    id: 'sl-013',
    ho_ten: 'Vì Văn Định',
    ma_can_bo: 'GV010',
    chuc_vu: 'Giáo viên',
    bo_phan: 'Tổ Khối 1 - Khối 2',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-11T14:15:00Z',
  },
  {
    id: 'sl-014',
    ho_ten: 'Quàng Văn Biên',
    ma_can_bo: 'GV011',
    chuc_vu: 'Giáo viên',
    bo_phan: 'Tổ Khối 3 - Khối 4',
    da_cai_dat: false,
    ngay_cai_dat: null,
  },
  {
    id: 'sl-015',
    ho_ten: 'Điển Thị Hương',
    ma_can_bo: 'GV012',
    chuc_vu: 'Giáo viên',
    bo_phan: 'Tổ Khối 3 - Khối 4',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-11T15:00:00Z',
  },
  {
    id: 'sl-016',
    ho_ten: 'Bùi Thị Dung',
    ma_can_bo: 'GV013',
    chuc_vu: 'Giáo viên',
    bo_phan: 'Tổ Khối 5',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-11T15:45:00Z',
  },
  {
    id: 'sl-017',
    ho_ten: 'Lê Thanh Bình',
    ma_can_bo: 'GV014',
    chuc_vu: 'Giáo viên',
    bo_phan: 'Tổ Khối 5',
    da_cai_dat: false,
    ngay_cai_dat: null,
  },

  // Khối Nhân Viên
  {
    id: 'sl-018',
    ho_ten: 'Cà Thị Thu',
    ma_can_bo: 'NV001',
    chuc_vu: 'Nhân viên',
    bo_phan: 'Văn phòng - Kế toán',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-10T14:00:00Z',
  },
  {
    id: 'sl-019',
    ho_ten: 'Lò Văn Tươi',
    ma_can_bo: 'NV002',
    chuc_vu: 'Nhân viên',
    bo_phan: 'Văn phòng - Thủ quỹ',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-10T14:30:00Z',
  },
  {
    id: 'sl-020',
    ho_ten: 'Vì Thị Thơm',
    ma_can_bo: 'NV003',
    chuc_vu: 'Nhân viên',
    bo_phan: 'Y tế trường học',
    da_cai_dat: false,
    ngay_cai_dat: null,
  },
  {
    id: 'sl-021',
    ho_ten: 'Lường Văn Toàn',
    ma_can_bo: 'NV004',
    chuc_vu: 'Nhân viên',
    bo_phan: 'Thiết bị - Thư viện',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-10T16:00:00Z',
  },
  {
    id: 'sl-022',
    ho_ten: 'Quàng Văn Hải',
    ma_can_bo: 'NV005',
    chuc_vu: 'Nhân viên',
    bo_phan: 'Bảo vệ - Thiết bị',
    da_cai_dat: false,
    ngay_cai_dat: null,
  },
  {
    id: 'sl-023',
    ho_ten: 'Cà Văn Long',
    ma_can_bo: 'NV006',
    chuc_vu: 'Nhân viên',
    bo_phan: 'Bán trú & Đời sống',
    da_cai_dat: true,
    ngay_cai_dat: '2026-08-11T09:00:00Z',
  },
];
